ALTER TABLE `customerspringquestions` ADD `springcataloglinkdate` DATE NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `springcataloglinkdate` `springcataloglinkdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `tradeshowsaregoingto` VARCHAR(1000) NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `tradeshowsaregoingto` `tradeshowsaregoingto` VARCHAR(1000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE `customerspringquestions` ADD `appointmentplace` VARCHAR(500) NOT NULL;
ALTER TABLE `customerspringquestions` ADD `ispoexpecting` TINYINT NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `ispoexpecting` `ispoexpecting` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `expectingpodate` DATE NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `expectingpodate` `expectingpodate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `isopportunitiessent` TINYINT NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `isopportunitiessent` `isopportunitiessent` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `opportunitiessentdate` DATE NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `opportunitiessentdate` `opportunitiessentdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `springsampledate` DATE NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `springsampledate` `springsampledate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `compshopcompletiondate` DATE NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `compshopcompletiondate` `compshopcompletiondate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `compshopsummeryemailsentdate` DATE NOT NULL; 
ALTER TABLE `customerspringquestions` CHANGE `compshopsummeryemailsentdate` `compshopsummeryemailsentdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `isreviewedsellthru` TINYINT NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `isreviewedsellthru` `isreviewedsellthru` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `isquotedforspring` TINYINT NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `isquotedforspring` `isquotedforspring` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `itemselectionfinalized` INT NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `itemselectionfinalized` `itemselectionfinalized` INT(11) NULL;
ALTER TABLE `customerspringquestions` ADD `finalizedtyvsly` VARCHAR(50) NOT NULL;
ALTER TABLE `customerspringquestions` CHANGE `finalizedtyvsly` `finalizedtyvsly` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE `customerspringquestions` ADD `itemspurchasedlastyear` INT NULL;
ALTER TABLE `customerspringquestions` ADD `isdinnerappt` TINYINT NULL;
ALTER TABLE `customerspringquestions` CHANGE `ispoexpecting` `arepoexpecting` VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE `customerspringquestions` ADD `dinnerapptplace` TEXT NULL;