ALTER TABLE `customerspringquestions` ADD `appointmentplace` VARCHAR(500) NOT NULL AFTER `tradeshowsaregoingto`;
ALTER TABLE `customerspringquestions` ADD `springcataloglinkdate` DATE NOT NULL AFTER `isallcategoriesselected`;
ALTER TABLE `customerspringquestions` CHANGE `springcataloglinkdate` `springcataloglinkdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `springsampledate` DATE NOT NULL AFTER `opportunitiessentdate`;
ALTER TABLE `customerspringquestions` CHANGE `springsampledate` `springsampledate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `compshopcompletiondate` DATE NOT NULL AFTER `appointmentplace`;
ALTER TABLE `customerspringquestions` CHANGE `compshopcompletiondate` `compshopcompletiondate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `compshopsummeryemailsentdate` DATE NOT NULL AFTER `compshopcompletiondate`; 
ALTER TABLE `customerspringquestions` CHANGE `compshopsummeryemailsentdate` `compshopsummeryemailsentdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `isreviewedsellthru` TINYINT NOT NULL AFTER `compshopsummeryemailsentdate`;
ALTER TABLE `customerspringquestions` CHANGE `isreviewedsellthru` `isreviewedsellthru` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `isquotedforspring` TINYINT NOT NULL AFTER `isreviewedsellthru`;
ALTER TABLE `customerspringquestions` CHANGE `isquotedforspring` `isquotedforspring` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `itemselectionfinalized` INT NOT NULL AFTER `isquotedforspring`;
ALTER TABLE `customerspringquestions` CHANGE `itemselectionfinalized` `itemselectionfinalized` INT(11) NULL;
ALTER TABLE `customerspringquestions` ADD `finalizedtyvsly` VARCHAR(50) NOT NULL AFTER `itemselectionfinalized`;
ALTER TABLE `customerspringquestions` CHANGE `finalizedtyvsly` `finalizedtyvsly` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE `customerspringquestions` ADD `ispoexpecting` TINYINT NOT NULL AFTER `finalizedtyvsly`;
ALTER TABLE `customerspringquestions` CHANGE `ispoexpecting` `ispoexpecting` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `expectingpodate` DATE NOT NULL AFTER `ispoexpecting`;
ALTER TABLE `customerspringquestions` CHANGE `expectingpodate` `expectingpodate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `isopportunitiessent` TINYINT NOT NULL AFTER `expectingpodate`;
ALTER TABLE `customerspringquestions` CHANGE `isopportunitiessent` `isopportunitiessent` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `isopportunitiessent` TINYINT NOT NULL AFTER `expectingpodate`;
ALTER TABLE `customerspringquestions` CHANGE `isopportunitiessent` `isopportunitiessent` TINYINT(4) NULL;
ALTER TABLE `customerspringquestions` ADD `opportunitiessentdate` DATE NOT NULL AFTER `isopportunitiessent`;
ALTER TABLE `customerspringquestions` CHANGE `opportunitiessentdate` `opportunitiessentdate` DATE NULL;
ALTER TABLE `customerspringquestions` ADD `tradeshowsaregoingto` VARCHAR(1000) NOT NULL AFTER `springcateloglinkdate`;
ALTER TABLE `customerspringquestions` CHANGE `tradeshowsaregoingto` `tradeshowsaregoingto` VARCHAR(1000) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE `customerspringquestions` ADD `itemspurchasedlastyear` INT NULL AFTER `springsampledate`;
ALTER TABLE `customerspringquestions` ADD `isdinnerappt` TINYINT NULL AFTER `itemspurchasedlastyear`;
ALTER TABLE `customerspringquestions` ADD `compshopsummeryemailsentdate` DATE NOT NULL AFTER `compshopcompletiondate`; 
ALTER TABLE `customerspringquestions` CHANGE `compshopsummeryemailsentdate` `compshopsummeryemailsentdate` DATE NULL;
ALTER TABLE `customerspringquestions` CHANGE `ispoexpecting` `arepoexpecting` VARCHAR(50) NULL DEFAULT NULL;
ALTER TABLE `customerspringquestions` ADD `dinnerapptplace` TEXT NULL AFTER `isdinnerappt`;